name: Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build docs
        run: cargo doc --all --no-deps --document-private-items 