name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  toml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@v1.12.5
      - name: Install taplo
        run: cargo binstall taplo-cli@0.9.3 --locked
      - name: Run Taplo
        run: taplo fmt --check --diff

  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Markdown Lint
        uses: super-linter/super-linter/slim@v7.3.0
        env:
          MULTI_STATUS: false
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MARKDOWN: true
          DEFAULT_BRANCH: main

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for typos
        uses: crate-ci/typos@v1.33.1 