name: MSRV

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.87.0
      - name: Check MSRV
        run: cargo check --all 